# Generated by Django 4.1.4 on 2023-01-12 03:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_title', models.CharField(max_length=50, verbose_name=' Tournament Name')),
                ('tournament_hastah', models.CharField(max_length=50, verbose_name=' Game Name')),
                ('tournament_content', ckeditor.fields.RichTextField(verbose_name='Tournament Views')),
                ('tournament_createddate', models.DateTimeField(auto_now_add=True, verbose_name=' Tournament Created Time')),
                ('tournament_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Tournament Image')),
                ('tournament_numberteam', models.IntegerField(verbose_name='Number of teams participating in the tournament')),
                ('tournament_numberinteam', models.IntegerField(verbose_name='Teams participating in the tournament')),
                ('tournament_price', models.IntegerField(verbose_name='Tournament entry fee')),
                ('tournament_status', models.IntegerField(verbose_name='Tournament Status')),
                ('tournament_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Turnuva sahibi')),
            ],
            options={
                'ordering': ['-tournament_createddate'],
            },
        ),
    ]
