# Generated by Django 4.1.4 on 2023-01-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_status',
            field=models.IntegerField(default=0, verbose_name='Tournament Status'),
        ),
    ]
