# Generated by Django 4.1.4 on 2023-03-03 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_tournament_numberintournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={},
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_round',
            field=models.IntegerField(default=0, verbose_name='Tournamanet Round'),
        ),
        migrations.CreateModel(
            name='TournamentTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_teamname', models.CharField(max_length=50, verbose_name='Tournament Team Name')),
                ('tt_createddate', models.DateTimeField(auto_now_add=True, verbose_name='This team join date in Tournament')),
                ('tt_tournamentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Tournament name')),
            ],
            options={
                'ordering': ['-tt_createddate'],
            },
        ),
    ]
