# Generated by Django 4.1.4 on 2023-05-25 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0005_tournament_tournament_1price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_image',
            field=models.FileField(blank=True, default='defaulttournament235.jpg', null=True, upload_to='', verbose_name='Tournament Image'),
        ),
        migrations.CreateModel(
            name='TournamentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_admin', models.CharField(max_length=50, verbose_name=' Staff Name')),
                ('admin_createddate', models.DateTimeField(auto_now_add=True, verbose_name='This team join date in Tournament')),
                ('admin_gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tournament Admin')),
                ('admin_tournamentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Tournament name')),
            ],
            options={
                'ordering': ['admin_createddate'],
            },
        ),
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminrequest_admin', models.CharField(max_length=50, verbose_name=' Staff Name')),
                ('adminrequest_status', models.IntegerField(verbose_name='Admin Status')),
                ('adminrequest_createddate', models.DateTimeField(auto_now_add=True, verbose_name='This team join date in Tournament')),
                ('adminrequest_gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tournament Admin')),
                ('adminrequest_tournamentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Tournament name')),
            ],
            options={
                'ordering': ['adminrequest_createddate'],
            },
        ),
    ]
