# Generated by Django 4.1.4 on 2023-05-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_rename_admin_admin_tournamentadmin_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentadmin',
            name='admin_status',
            field=models.IntegerField(max_length=50, verbose_name=' Staff Name'),
        ),
    ]
