# Generated by Django 4.1.4 on 2023-05-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_tournamentadmin_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentadmin',
            name='admin_status',
            field=models.IntegerField(verbose_name=' Staff Name'),
        ),
        migrations.CreateModel(
            name='TournamentMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_team1', models.CharField(max_length=50, verbose_name=' Team1')),
                ('tm_team2', models.CharField(max_length=50, verbose_name=' Team2')),
                ('tm_createddate', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('tm_status', models.IntegerField(default=0, verbose_name='Match Status')),
                ('tm_tournamentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Tournament name')),
            ],
            options={
                'ordering': ['tm_tournamentname'],
            },
        ),
    ]
