# Generated by Django 4.1.4 on 2023-05-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_tournamentadmin_admin_status_tournamentmatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatches',
            name='tm_round',
            field=models.IntegerField(default=0, verbose_name='Tournament Round'),
        ),
    ]
