# Generated by Django 4.1.4 on 2023-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_tournamentmatches_tm_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatches',
            name='tm_round',
            field=models.IntegerField(default=1, verbose_name='Tournament Round'),
        ),
    ]
