# Generated by Django 4.1.4 on 2023-06-10 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0011_alter_tournamentmatches_tm_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_message', models.CharField(max_length=50, verbose_name='Message Text')),
                ('tc_createddate', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('tc_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comment user')),
                ('tc_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Tournament name')),
            ],
        ),
    ]
